Guess worker count, make thread pool size configurable
Guess worker count while making sure we don't allocate too much memory.
Add two configuration variables for determining Puma's thread pool size,
`PUMA_MIN_THREADS` and `PUMA_MAX_THREADS`. By default we try to detect
memory limits using cgroups and compute the correct number of maximum
threads from that.

diff --git a/2.0/s2i/bin/run b/2.0/s2i/bin/run
--- a/2.0/s2i/bin/run
+++ b/2.0/s2i/bin/run
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+function export_memory_limit() {
+  if [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ]; then
+    export MEMORY_LIMIT_IN_BYTES=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
+    return 0
+  fi
+  return 1
+}
+
+function export_number_of_cores() {
+  if [ -f /sys/fs/cgroup/cpuset/cpuset.cpus ]; then
+    export NUMBER_OF_CORES=`awk ' \
+      BEGIN { i = 0; FS="-"; RS="[,\n]" } \
+      /^[0-9]+-[0-9]+$/ { i += $2-$1+1 }  \
+      /^[0-9]+$/        { ++i }           \
+      END { print i} \
+      ' /sys/fs/cgroup/cpuset/cpuset.cpus`
+    return 0
+  fi
+  return 1
+}
+
 function is_puma_installed() {
   [ ! -f Gemfile.lock ] && return 1
   grep ' puma ' Gemfile.lock >/dev/null
@@ -10,6 +31,12 @@ set -e
 export RACK_ENV=${RACK_ENV:-"production"}
 
 if is_puma_installed; then
+  if ! export_memory_limit; then
+    echo "Warning: Can't detect memory limit"
+  fi
+  if ! export_number_of_cores; then
+    echo "Warning: Can't detect number of cores"
+  fi
   exec bundle exec "puma --config ../etc/puma.cfg"
 else
   echo "You might consider adding 'puma' into your Gemfile."
